language: php

php:
  - 5.2
  - 5.3

env:
  - OMEKA_BRANCH=stable-1.5
  - OMEKA_BRANCH=master

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - ./.travis.setup.sh

script: ./.travis.tests.sh

#notifications:
  #irc: "irc.freenode.org#slab"
